"""e4m3_compose.py <calib|serve> <run dir name> <overlay dir name> : write the compose file of one step of the
E4M3-KV + MTP bring-up of the fork on GPU 4-7, derived from the production 8031 compose (GPU 0-3, not touched).

calib : MTP k=4, FP16 KV, eager, 40960 context, 2048-token step, QSA K/V observer writing to
        /calib/<run dir name>; 127.0.0.1:8141 only.
        -> /mnt/2t/build/mtp_kv/compose.e4m3-calib.yaml
serve : MTP k=4, calibrated E4M3 KV read from /models/<overlay dir name>; 127.0.0.1:8141 and 0.0.0.0:8011.
        -> /opt/shixiang-inference/docker-dflash2/compose.swift15-flashnext-mtp-e4m3-tp4-gpu4567.yaml

Both use image heavily-modified-v1-0930-r1 (fork tag 1cat-vllm-heavily-modified-v1-0930 plus branch sx/mtp-memory,
Python files only) and gpu_memory_utilization 0.87; serve keeps production's 131072 context and 8192-token step."""
import re
import sys

SRC = "/opt/shixiang-inference/docker-dflash2/compose.swift15-flashnext-tp4-gpu0123.yaml"
IMAGE = "shixiang/1cat-vllm-v100:heavily-modified-v1-0930-r1"
mode, run, overlay = sys.argv[1:4]
assert mode in ("calib", "serve"), mode
s = open(SRC).read()


def sub(pattern, repl):
    global s
    s, n = re.subn(pattern, lambda m: repl, s, count=1, flags=re.M)
    assert n == 1, pattern


def env(key, value):
    global s
    s = re.sub(r"(?m)^      %s: .*\n" % re.escape(key), "", s)
    m = re.search(r"(?m)^    environment:\n", s)
    s = s[:m.end()] + '      %s: "%s"\n' % (key, value) + s[m.end():]


name = "sx-e4m3-calib" if mode == "calib" else "shixiang-inference-swift15-flashnext-mtp-e4m3-tp4"
sub(r"^name: .*$", "name: %s" % ("sx-e4m3-calib" if mode == "calib" else "sx-flashnext-mtp-e4m3"))
sub(r"^    image: .*$", "    image: %s" % IMAGE)
sub(r"^    container_name: .*$", "    container_name: %s" % name)
sub(r"^    restart: .*$", '    restart: "no"')
sub(r'^    ports: \["0\.0\.0\.0:8031:8001"\]$',
    '    ports: ["127.0.0.1:8141:8001"]' if mode == "calib"
    else '    ports: ["127.0.0.1:8141:8001", "0.0.0.0:8011:8001"]')
sub(r"source: /opt/shixiang-inference/cache-flashnext-tp4, target: /cache",
    "source: /opt/shixiang-inference/cache-mtp-test-tp4, target: /cache")
sub(r"^      GPU_MEMORY_UTILIZATION: .*$", '      GPU_MEMORY_UTILIZATION: "0.87"')
sub(r"^      MTP_SPECULATIVE_TOKENS: .*$", '      MTP_SPECULATIVE_TOKENS: "4"')
sub(r"^      VLLM_SM70_NVFP4_MOE_TUNE_MAX_TOKENS: .*$", '      VLLM_SM70_NVFP4_MOE_TUNE_MAX_TOKENS: "1200"')
sub(r'^              device_ids: \["0","1","2","3"\]$', '              device_ids: ["4","5","6","7"]')
if mode == "calib":
    env("VLLM_QSA_KV_CALIBRATION_DIR", "/calib/%s" % run)
    # Eager profiling of an 8192-token step leaves 0.9 GiB for the KV cache (131072 context needs 2.0 GiB), so the
    # calibration instance runs upstream's calibration step size and a 40960 context.
    sub(r"^      MAX_MODEL_LEN: .*$", '      MAX_MODEL_LEN: "40960"')
    sub(r"^      MAX_NUM_BATCHED_TOKENS: .*$", '      MAX_NUM_BATCHED_TOKENS: "2048"')
    m = re.search(r"(?m)^    volumes:\n", s)
    s = s[:m.end()] + "      - {type: bind, source: /mnt/2t/build/mtp_kv/calib, target: /calib}\n" + s[m.end():]
    m = re.search(r"(?m)^      - --language-model-only.*\n", s)
    s = s[:m.end()] + "      - --enforce-eager   # the K/V observer is Python; a CUDA graph replay would skip it\n" \
        + s[m.end():]
    out = "/mnt/2t/build/mtp_kv/compose.e4m3-calib.yaml"
    head = "# K/V calibration instance for the E4M3 QSA KV cache (see e4m3_chain.sh). Temporary.\n"
else:
    sub(r"^      MODEL_PATH: .*$", "      MODEL_PATH: /models/%s" % overlay)
    sub(r"^      KV_CACHE_DTYPE: .*$", "      KV_CACHE_DTYPE: fp8_e4m3   # calibrated E4M3 QSA KV (24 target + 2 MTP scales)")
    env("VLLM_QWEN4EXP_QSA_E4M3_STRICT_SCALES", "1")
    env("VLLM_QWEN4EXP_QSA_E4M3_MTP", "1")
    out = "/opt/shixiang-inference/docker-dflash2/compose.swift15-flashnext-mtp-e4m3-tp4-gpu4567.yaml"
    head = (
        "# 2026-09-30 Swift-1.5 Flash-Next on GPU 4-7: fork 1cat-vllm-heavily-modified-v1-0930 + sx/mtp-memory\n"
        "# (PLE prefill two buffers = upstream PR #707, calibrated E4M3 QSA KV with MTP = upstream PR #664),\n"
        "# native MTP k=4, E4M3 KV from the overlay checkpoint /mnt/2t/models/%s\n"
        "# (scales calibrated on this server, /mnt/2t/build/mtp_kv/calib). Generated by\n"
        "# /mnt/2t/build/mtp_kv/e4m3_compose.py from the production 8031 compose; the comments below are\n"
        "# production's and describe the no-MTP lane.\n" % overlay)
open(out, "w").write(head + s)
print(out)
