"""Write the GPU 4-7 compose that serves the fork's wheel-built image (built from source with the repository's
docker/Dockerfile, see /mnt/2t/build/fork-wheel-1001/build_fork.sh) with production's flags and environment, to
check the wheel against the production image on 8031. Derived from the 8031 compose: same checkpoint, served name,
serve flags and every fork environment switch; no MTP. Differences that come from the image: upstream entrypoint
`vllm serve` (no /app scripts), the image's own CUDA toolkit, curl health check, a fresh cache directory (first start
compiles everything, as it would for someone who installs the wheel)."""
import re

SRC = "/opt/shixiang-inference/docker-dflash2/compose.swift15-flashnext-tp4-gpu0123.yaml"
DST = "/opt/shixiang-inference/docker-dflash2/compose.forkwheel-flashnext-tp4-gpu4567.yaml"
IMAGE = "shixiang/1cat-vllm-v100:heavily-modified-v1-1001-sm70main"
s = open(SRC).read()


def sub(pattern, repl, count=1):
    global s
    s, n = re.subn(pattern, repl, s, count=count, flags=re.M)
    assert n == count, (pattern, n)


first_key = s.index("\nname: ")
s = ("# GPU 4-7, ports 8011 and 127.0.0.1:8141: the fork built from source as a wheel (image %s,\n"
     "# fork branch 1cat-vllm-heavily-modified-v1), production flags and environment, no MTP. Generated by\n"
     "# /mnt/2t/build/fork-wheel-1001/mk_forkwheel_compose.py from the 8031 compose.\n" % IMAGE
     + s[first_key:])
sub(r"^name: .*$", "name: shixiang-forkwheel-flashnext-tp4")
sub(r"^  [a-z0-9-]+:\n(?=(?:    #.*\n)*    image: )", "  forkwheel-flashnext-tp4:\n")
s = re.sub(r"(  forkwheel-flashnext-tp4:\n)(?:    #.*\n)+", r"\1", s, count=1)
sub(r"^    image: .*$", "    image: " + IMAGE)
sub(r"^    container_name: .*$", "    container_name: shixiang-inference-forkwheel-flashnext-tp4")
sub(r"^    restart: .*$", '    restart: "no"')
sub(r'^    ports: \["0\.0\.0\.0:8031:8001"\]$', '    ports: ["127.0.0.1:8141:8001", "0.0.0.0:8011:8001"]')
sub(r"^      - \{type: bind, source: /opt/shixiang-inference/cache-flashnext-tp4, target: /cache\}$",
    "      - {type: bind, source: /opt/shixiang-inference/cache-forkwheel-flashnext-tp4, target: /cache}")
sub(r"^      - \{type: bind, source: /usr/local/cuda-12\.8, target: /usr/local/cuda, read_only: true\}\n", "")
sub(r"^      - \{type: bind, source: /opt/shixiang-aihub/deploy/inference/entrypoint\.sh, target: /app/entrypoint\.sh, read_only: true\}\n", "")
# Variables read only by the production entrypoint script; the flags below carry their values.
for key in ("MODEL_PATH", "SERVED_MODEL_NAME", "QUANTIZATION", "VLLM_HOST", "VLLM_PORT", "TENSOR_PARALLEL_SIZE",
            "MAX_MODEL_LEN", "MAX_NUM_SEQS", "MAX_NUM_BATCHED_TOKENS", "GPU_MEMORY_UTILIZATION", "KV_CACHE_DTYPE",
            "ATTENTION_BACKEND", "MTP_METHOD", "MTP_SPECULATIVE_TOKENS", "DFLASH_MODEL", "CUDA_HOME"):
    sub(r"^      %s: .*\n" % key, "")
sub(r'^              device_ids: \["0","1","2","3"\]$', '              device_ids: ["4","5","6","7"]')
sub(r'^      test: \["CMD", "/app/healthcheck\.sh"\]$',
    '      test: ["CMD-SHELL", "curl -sf http://127.0.0.1:8001/health >/dev/null || exit 1"]')
tail = s.index('    entrypoint: ["/app/entrypoint.sh"]')
flags = """    entrypoint: ["vllm", "serve"]
    command:
      - /models/Swift-1.5-Qwen3.8-Flash-Next-NVFP4
      - --served-model-name=Swift-1.5-Qwen3.8-Flash-Next
      - --host=0.0.0.0
      - --port=8001
      - --tensor-parallel-size=4
      - --dtype=half
      - --attention-backend=FLASH_ATTN_V100
      - --max-model-len=131072
      - --max-num-seqs=24
      - --max-num-batched-tokens=8192
      - --gpu-memory-utilization=0.90
      - --kv-cache-dtype=auto
      - --trust-remote-code
      - --enable-prefix-caching
      - --enable-chunked-prefill
      - --enable-auto-tool-choice
      - --tool-call-parser=qwen3_coder
      - --reasoning-parser=qwen3
      - --language-model-only
"""
s = s[:tail] + flags
open(DST, "w").write(s)
print("written", DST)
